sudo: required
services:
  - docker

before_install:
  - docker build -t brksdeadpool/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run brksdeadpool/react-test npm test -- --coverage

after_success:
  - docker build -t brksdeadpool/fib-client -f ./client/Dockerfile ./client
  - docker build -t brksdeadpool/fib-nginx -f ./nginx/Dockerfile ./nginx
  - docker build -t brksdeadpool/fib-server -f ./server/Dockerfile ./server
  - docker build -t brksdeadpool/fib-worker -f ./worker/Dockerfile ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push brksdeadpool/fib-client
  - docker push brksdeadpool/fib-nginx
  - docker push brksdeadpool/fib-server
  - docker push brksdeadpool/fib-worker

deploy:
  provider: elasticbeanstalk
  region: sa-east-1
  app: docker-fib
  env: DockerFib-env
  bucket_name: elasticbeanstalk-sa-east-1-480162803178
  bucket_path: fib
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
